#!/usr/bin/env python3.11
"""Regenerate the per-project handoff rollups.

WHY THIS EXISTS
---------------
NotebookLM's Standard tier caps a notebook at 50 sources. Session handoffs are
the fastest-growing page class in the vault and the shortest-lived: a handoff's
purpose expires the moment the next session starts. Left alone they consume one
slot each until the notebook wedges — cdaa7a43 crossed 50 on 2026-07-29 07:57
and every sync afterwards reported `upload_failed: 16`.

The established remedy is CONSOLIDATION, not deletion (Matt's directive; same
pattern as the-match vault's wiki/synthesis/handoffs-rollup.md, 2026-07-06):
combine the individual handoffs into ONE source per project notebook, exclude
the individuals from every notebook, and keep the individual files on disk and
in git as the primary read path. Nothing is lost — the files stay, Pinecone
still has full-text recall over them, and they stop occupying slots.

This is a GENERATOR rather than a hand-maintained page on purpose. The-match's
rollup is regenerated by hand "whenever a new handoff is written", which is a
standing invitation to drift. Run this instead:

    python3.11 tools/notebooklm-rollup.py            # rewrite the rollups
    python3.11 tools/notebooklm-rollup.py --check    # exit 1 if stale (for preflight)

Members are concatenated VERBATIM, newest first. Verbatim matters: summarising
24 handoffs by hand would quietly drop the load-bearing details (open items,
next steps, retractions) that are the only reason to keep a handoff at all.

ADDING A NEW HANDOFF: append its path to the right group below and re-run. If a
handoff belongs to a project whose pages already route home by prefix, prefer
naming it so it routes itself; this rollup is for the ones that would otherwise
land in the general bucket.
"""
import argparse
import json
import re
import sys
from pathlib import Path

VAULT = Path(__file__).resolve().parent.parent

# ── Rollup groups ────────────────────────────────────────────────────────────
# The rollup FILENAMES are chosen so they route themselves with the prefixes
# already in .limitless-project.py — no new route entries needed:
#   wiki/synthesis/openfirehouse-*  → 9c8f3df0 (OpenFirehouse Project Docs)
#   wiki/synthesis/hub-*            → ca083f4f (Limitless Stack Hub - Repo)
# Members are listed newest-first; the first one is marked [ACTIVE].
ROLLUPS = {
    "wiki/synthesis/openfirehouse-handoffs-rollup.md": {
        "tags": "[openfirehouse, harden-the-tail, handoff, rollup]",
        "title": "OpenFirehouse — handoff rollup",
        "blurb": (
            "Every OpenFirehouse session/phase handoff, newest first, in one NotebookLM\n"
            "source. Covers the HARDEN-THE-TAIL program (Phases 1–5), Prevention, the\n"
            "accountability build, the LEITSC gap analysis, and the June multi-tenant\n"
            "sessions. Trust the [ACTIVE] section; everything below it is superseded\n"
            "history, kept because the retractions and open items in it are load-bearing."
        ),
        "members": [
            "wiki/synthesis/handoff-hardentail-2026-08-01.md",
            "wiki/synthesis/handoff-phase3-2026-07-27-pm.md",
            "wiki/synthesis/handoff-phase3-2026-07-27.md",
            "wiki/synthesis/handoff-phase3-31a-2026-07-27.md",
            "wiki/synthesis/handoff-phase3-2026-07-26.md",
            "wiki/synthesis/handoff-phase4-2026-07-26.md",
            "wiki/synthesis/handoff-hardentail-2026-07-25b.md",
            "wiki/synthesis/handoff-hardentail-2026-07-25.md",
            "wiki/synthesis/handoff-hardentail-1_1c-shipped-2026-07-23.md",
            "wiki/deliverables/HANDOFF-prevention-offline-2026-07-14.md",
            "wiki/synthesis/handoff-accountability-2026-07-13.md",
            "wiki/synthesis/leitsc-gap-analysis-2026-07-12.md",
            "wiki/synthesis/session-handoff-2026-06-15.md",
            "wiki/synthesis/session-handoff-2026-06-14.md",
            "wiki/synthesis/session-handoff-2026-06-13.md",
        ],
    },
    "wiki/synthesis/hub-handoffs-rollup.md": {
        "tags": "[limitless-stack-hub, hermes, paperclip, handoff, rollup]",
        "title": "Limitless Stack Hub / Paperclip / Hermes — handoff rollup",
        "blurb": (
            "Every Hub-side session handoff, newest first, in one NotebookLM source:\n"
            "Stack + loop-engineering sessions, the Paperclip→Hermes cutover, model\n"
            "allocation, and the NotebookLM sync forensics. Paperclip and Hermes pages\n"
            "already route to this notebook per .limitless-project.py, so their handoffs\n"
            "belong here too. Trust the [ACTIVE] section; the rest is superseded history."
        ),
        "members": [
            "wiki/deliverables/HANDOFF-notebooklm-forensics-2026-08-01.md",
            "wiki/synthesis/handoff-paperclip-hermes-cutover-2026-07-27.md",
            "wiki/synthesis/paperclip-prod-reconciliation-2026-07-26.md",
            "wiki/synthesis/session-handoff-2026-07-25.md",
            "wiki/synthesis/session-handoff-2026-07-25-paperclip-models.md",
            "wiki/synthesis/free-model-selection-2026-07-25.md",
            "wiki/synthesis/session-handoff-2026-07-23.md",
            "wiki/synthesis/session-handoff-2026-07-22.md",
            "wiki/synthesis/hermes-plan-audit-2026-07-12.md",
            # Cross-app (Hub + OpenRestaurant + the design apps came off the OF DB).
            # Filed here rather than with OpenFirehouse because the work was moving
            # everything OFF OpenFirehouse's database — it is OpenScaffold infra.
            "wiki/synthesis/openscaffold-db-separation-runbook-2026-06-13.md",
        ],
    },
}


def all_members() -> list[str]:
    """Every path consolidated by any rollup — what must be excluded from
    routing. Imported by the preflight so the two can never disagree."""
    return [m for spec in ROLLUPS.values() for m in spec["members"]]


# Handoffs that deliberately belong to NO rollup. Anything else matching the
# handoff shape and missing from every rollup is reported by --check as ORPHANED.
# Keep this list short and justified — it is an allowlist, not a dumping ground.
ROLLUP_EXEMPT = {
    # The rollups themselves are not members of themselves.
    "wiki/synthesis/openfirehouse-handoffs-rollup.md",
    "wiki/synthesis/hub-handoffs-rollup.md",
}


def _individually_tracked() -> set[str]:
    """Paths that already have their OWN source in some notebook, per the state files.

    A handoff reaches a notebook one of two legitimate ways: consolidated into a
    rollup, or routed individually. Only a page in NEITHER is actually uncovered.
    """
    # The except is DELIBERATELY NARROW. The first draft caught bare `Exception` and
    # `continue`d — and `json` was not imported, so every file raised NameError, the
    # handler swallowed it, and this returned an empty set. The orphan report then
    # confidently listed 10 healthy files. A broad except turns a bug into a silent
    # wrong answer, which is the whole disease this session has been chasing.
    tracked: set[str] = set()
    files = sorted(VAULT.glob("tools/.notebooklm-*-state.json"))
    if not files:
        print("  ! no notebooklm state files found — orphan detection cannot be trusted",
              file=sys.stderr)
    for f in files:
        try:
            tracked |= set(json.loads(f.read_text()).keys())
        except (OSError, json.JSONDecodeError) as e:
            # Unreadable state is a real problem, not something to skip quietly: it makes
            # every path in that bucket look orphaned. Say so and keep going.
            print(f"  ! could not read {f.name} ({e}) — paths it tracks may be "
                  f"reported as orphans", file=sys.stderr)
    return tracked


def find_orphans() -> list[str]:
    """Handoff-shaped wiki pages that reach NO notebook — neither rolled up nor routed.

    WHY THIS EXISTS: `members` above is a HARDCODED list, so writing a new handoff does
    NOT add it to a rollup — and until 2026-08-01 nothing noticed. `--check` only
    compared listed members against their generated output, so a handoff that was never
    listed was, by construction, always "up to date". Its first run caught the handoff
    written that same day, already orphaned.

    Same bug shape as everything else this session: a structure that can only report on
    what it already knows about cannot report what is MISSING from it. The invariant has
    to be computed from the world, never from the tracking structure.

    ⚠ AND THE FIRST VERSION OF THIS FUNCTION CRIED WOLF — it flagged 10 handoffs as
    orphaned when all 10 were individually routed and present in notebooks. Checking
    rollup membership alone measures the wrong thing. A check that fires on healthy state
    is worse than no check: it trains everyone to ignore it, which is the exact failure
    this file's own history is about. Hence `_individually_tracked()`.
    """
    known = set(all_members()) | ROLLUP_EXEMPT | _individually_tracked()
    orphans: list[str] = []
    for pat in ("wiki/synthesis/*handoff*.md", "wiki/deliverables/*HANDOFF*.md",
                "wiki/synthesis/session-handoff-*.md"):
        for p in sorted(VAULT.glob(pat)):
            rel = p.relative_to(VAULT).as_posix()
            if rel not in known and rel not in orphans:
                orphans.append(rel)
    return orphans


def render(rel_out: str, spec: dict) -> str:
    today = "2026-08-01"
    out = [
        "---",
        "type: synthesis",
        f"created: {today}",
        f"updated: {today}",
        f"tags: {spec['tags']}",
        "generated_by: tools/notebooklm-rollup.py",
        "---",
        "",
        f"# {spec['title']}",
        "",
        "> **GENERATED FILE — do not hand-edit.** Regenerate with",
        "> `python3.11 tools/notebooklm-rollup.py` after writing a new handoff, and add the",
        "> new handoff to `ROLLUPS` in that script. The individual handoff files remain on",
        "> disk and in git as the primary read path; this is the single NotebookLM source",
        "> that stands in for all of them under the 50-source cap.",
        "",
        spec["blurb"],
        "",
    ]
    missing = []
    for i, rel in enumerate(spec["members"]):
        p = VAULT / rel
        if not p.exists():
            missing.append(rel)
            continue
        marker = "[ACTIVE] " if i == 0 else ""
        out += [
            "",
            "---",
            "",
            f"# {marker}{Path(rel).name}",
            f"<!-- source: {rel} -->",
            "",
            p.read_text().rstrip(),
            "",
        ]
    if missing:
        print(f"  ! {rel_out}: {len(missing)} member(s) missing on disk:", file=sys.stderr)
        for m in missing:
            print(f"      {m}", file=sys.stderr)
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="don't write; exit 1 if any rollup is out of date")
    args = ap.parse_args()

    stale = False
    for rel_out, spec in ROLLUPS.items():
        target = VAULT / rel_out
        new = render(rel_out, spec)
        cur = target.read_text() if target.exists() else None
        # Ignore the `updated:` line when comparing, so --check doesn't report
        # staleness purely because the stamp moved.
        def _norm(s: str | None) -> str:
            return re.sub(r"^updated: .*$", "", s or "", flags=re.M)
        if _norm(cur) == _norm(new):
            print(f"  = {rel_out} up to date ({len(spec['members'])} members)")
            continue
        stale = True
        if args.check:
            print(f"  ✗ {rel_out} is STALE", file=sys.stderr)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(new)
            kb = len(new) // 1024
            print(f"  ✓ wrote {rel_out}  ({len(spec['members'])} members, {kb} KB)")
    # Computed from the FILESYSTEM, not from ROLLUPS — see find_orphans()'s docstring.
    # A handoff nobody listed would otherwise be "up to date" forever by construction,
    # and would silently never reach a notebook.
    orphans = find_orphans()
    if orphans:
        print(f"  ! {len(orphans)} handoff(s) belong to NO rollup:", file=sys.stderr)
        for rel in orphans:
            print(f"      {rel}", file=sys.stderr)
        print("    Add each to a rollup's `members` (newest first), or to ROLLUP_EXEMPT "
              "with a reason.", file=sys.stderr)
    else:
        print(f"  = every handoff belongs to a rollup ({len(all_members())} members total)")

    if args.check and (stale or orphans):
        if stale:
            print("rollups are stale — run tools/notebooklm-rollup.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
